config/routes.rb
Rails.application.routes.draw do
  get 'pages/home'

  get 'pages/about'

  get 'pages/directions'

  resources :articles do
    resources :comments
  end
  resources :users

  root 'users#index'

end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :user
  has_many :comments
  validates :title, presence: true,
            length: {maximum: 50}
  validates :post, presence: true
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :articles
  validates :password, presence: true,
            length: { minimum: 8}
  validates :email, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:title, :post, :user_id)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  # After comment creation, we redirect back to the article
  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.create(comment_params)
    redirect_to article_path(@article)
  end

  private
  def comment_params
    params.require(:comment).permit(:commenter, :body)
  end
end

app/controllers/index_controller.rb
class IndexController < ApplicationController
  def index
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def directions
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:password, :email)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    if(params.has_key?(:id) && params.has_key?(:random))
      @id = params['id']
      @random = params[:random]
    end
  end
  def beyblade
    @controller_message = "Hello From Controller"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def get_season()
      # year - gets you the numerical year
      # month - gets you the numberical value of the month
      # day - gets you the day
      # wday - gets you 0 - 6
      # yday - gets you 0 - 365
      # hour - gets you 0 - 24
      # sec - gets you 0 - 59
      # min - gets you 0 - 59
      # zone - gets you the timezone


    time = Time.new

    if(time.month >= 3) && (time.month <= 5)
      "Yeah it is Spring"
    elsif(time.month > 5) && (time.month <= 8)
      "Everyone Loves Summer"
    elsif(time.month > 8) && (time.month <= 10)
      "Put on your coat because FAll is here"
    else
      "Winter is here!"
    end
  end

  def get_random_number(max_value = 10)
    rand(max_value)
  end

  def get_random_welcome()
    opening = ["What a beautiful day. ",
               "Welcome to our site. ",
               "Thank you for stopping by. "]

    middle = ["We hope you find what you need. ",
               "We have a wide selection. ",
               "Check out our sale items. "]

    ending = ["Contact us if you need help. ",
               "We are here to serve you. ",
               "Call us if you need to 412-555-1212. "]

    "#{opening[rand(3)]} #{middle[rand(3)]} #{ending[rand(3)]}"
  end

  def count_to_10
    x=2
    number_list = "1"

    loop do
      number_list = number_list + ", " + x.to_s
      x += 1
      break if x > 10
    end
    "#{number_list}"
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% @article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :post %><br>
    <%= f.text_area :post %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing Article</h1>

<%= render 'form' %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Articles</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Post</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @articles.each do |article| %>
  <!-- This will make each row in the table have a different class name -->
      <tr class="<% cycle('list_line_odd', 'list_line_even') %>">
        <td><%= article.title %></td>
        <td><%= article.post %></td>
        <td><%= article.user_id %></td>
        <td><%= link_to 'Show', article %></td>
        <td><%= link_to 'Edit', edit_article_path(article) %></td>
        <td><%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Article', new_article_path %>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>

<p>
  <strong>Post:</strong>
  <%= @article.post %>
</p>

<p>
  <strong>User:</strong>
  <%= @article.user_id %>
</p>


<h2>Comments</h2>
<% @article.comments.each do |comment| %>
    <p>
        <strong>Commenter:</strong>
        <%= comment.commenter %>
    </p>
    <p>
      <strong>Comment:</strong>
      <%= comment.body %>
    </p>
<% end %>

<h2>Add a Comment:</h2>
<%= form_for([@article, @article.comments.build]) do |f| %>
  <p>
    <%= f.label :commenter %><br />
    <%= f.text_field :commenter %>
  </p>

    <p>
      <%= f.label :body %><br />
      <%= f.text_field :body %>
    </p>

    <p>
      <%= f.submit %>
    </p>
    <% end %>

<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>

app/views/index/index.html.erb
<h1>Welcome Here</h1>
<h1>Find me in app</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title> <%= yield(:title) %></title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div id="wrapper">
<header>
  <%= link_to image_tag("bridge.jpg", alt: "Cool Bridge", :width => 140),
              {:controller => 'pages', :action => 'home'},
              {:class => 'websiteLogo'} %>
  <%= link_to 'Rails Test', {:controller => 'pages', :action => 'home'},
              {:class => 'websiteTitle'}%>
<nav id="horizNav">
  <p>
    <%= link_to 'Home', {:controller => 'pages', :action => 'home'} %>
    <%= link_to 'About', {:controller => 'pages', :action => 'about'} %>
    <%= link_to 'Directions', {:controller => 'pages', :action => 'directions'} %>
    <%= link_to 'Articles', {:controller => 'articles', :action => 'index'} %>
    <%= link_to 'Users', {:controller => 'users', :action => 'index'} %>
  </p>
</nav>
</header>
  <main id="content">
  <%= yield %>
  </main>
</div> <!-- End of Wrapper -->
</body>
</html>

app/views/pages/about.html.erb
<% provide(:title, "About Us") %>
<h1>About Us</h1>
<p>We love what we do and do what we love.</p>
<p>
  <a href="mailto:fernando@example.com?Subject=I%20need%20help">Contact Fernando for Help</a>
</p>

app/views/pages/directions.html.erb
<% provide(:title, "Directions") %>
<h1>Directions</h1>
<p>Directions to our place</p>

app/views/pages/home.html.erb
<% provide(:title, "Welcome") %>
<h1>Home</h1>
<p>Welcome to our home page</p>
<p><%= get_season %></p>
<p><%= get_random_number(1000) %></p>
<p><%= get_random_welcome %></p>
<p><%= count_to_10 %></p>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :password %><br>
    <%= f.text_field :password %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Password</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.password %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Password:</strong>
  <%= @user.password %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>

<%# Comment %>

<%= "Count to 10" %>
<br/>
<% 11.times do |i|  %>
  <%= i %>
<% end %>

<br/>

<% if(params.has_key?(:id) &&
      params.has_key?(:random)) %><br/>
    <%= "ID : #{params[:id]}" %><br/>
    <%= "RANDOM :  #{params[:random]}" %><br/>
  <%end%>



<br/>

<%

  a = "7".to_i

  puts case a
         when 1..5
%><%="It's between 1 and 5"%><%
         when 6
%><%="It's 6"%><%
         when String
%><%="You passed a string"%><%
         else
%><%="You gave me #{a} -- I have no idea what to do with that."%><%
       end
  %>